### ISSUE TITLE
Pins Map and Schematcs Board

### ISSUE THREAD

**Issue by acguardia** [Creality3DPrinting/CR10-V2#6]
I need the schematics, pins maps and PCB layout to this board. I can't find it in anywheare.

![creality-cr-10-v2-motherboard-v252](https://user-images.githubusercontent.com/10907735/115657010-8fa7b580-a30c-11eb-9a5d-661684b1c82d.jpg)

**Comment by biarkiw** [comment]
Yeah, I'm looking to update mine to Marlin 2.0 since there isn't a provided firmware for that version as of yet

**Comment by aleohl** [comment]
Seems like it's not open source, check #4

**Comment by acguardia** [comment]
Not Open Source
